import "server-only";

import { mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { db } from "@/lib/db";
import {
  countListingsByCategory,
  countListingsByCityState,
  countListingsByIndustry,
  directoryImagePath,
  listingLogoPath,
  loadPublishedListings,
  slugify,
} from "@/lib/directory";
import { categoryPath } from "@/lib/directory-category-labels";
import { locationLabel, locationPath } from "@/lib/directory-location-labels";
import { industryPath } from "@/lib/directory-industry-labels";
import {
  DEFAULT_DIRECTORY_LOCALE,
  DIRECTORY_LOCALES,
  directoryCategoriesIndexPath,
  directoryHomePath,
  directoryListingFaqPath,
  directoryListingNewsPath,
  directoryListingPath,
  directoryListingPhotosPath,
  directoryListingPromotionsPath,
  directoryListingServicesPath,
  directoryListingVideosPath,
  directoryListingVisitPath,
  directoryLocationsIndexPath,
  directoryNewsPath,
  directoryProductsPath,
  type DirectoryLocale,
} from "@/lib/directory-i18n";
import { STATIC_SEO_ORIGIN } from "@/lib/static-seo-origin";

// This used to be src/app/sitemap.ts, a Next.js route rendering
// sitemap.xml fresh on every request. Moved to a plain static file (see
// /public) generated ahead of time instead — regenerated by every action
// that changes what belongs in it (publishListing/unpublishDirectoryListing
// in src/app/actions/directory.ts) rather than rendered per request.
// instrumentation.ts also regenerates it once on server startup,
// so an accidentally-stale file self-heals without needing to wait for the
// next publish/unpublish.
//
// /public/sitemap.xml IS committed to git (a minimal placeholder — see
// that file) despite being generated content, unlike this repo's other
// runtime-written /public files (e.g. /public/uploads/, gitignored).
// That's not a style choice: Next.js decides which /public paths exist at
// `next build` time, baked into that build's own output — a file that
// didn't exist yet at build time can never be served afterward, no matter
// what writes it at runtime, until the *next* build. A gitignored
// sitemap.xml would 404 forever on this app's very first deploy after this
// feature shipped. Once the path exists in at least one build, though,
// every later request reads the file's current content fresh off disk —
// which is what makes overwriting it at runtime (regenerateSitemapFile,
// below) work at all after that.
const SITEMAP_PATH = path.join(process.cwd(), "public", "sitemap.xml");

// The same set each page's own <head> declares (see buildLanguageAlternates
// in directory-seo.ts): all three languages plus x-default → English.
function languageAlternates(pathFor: (locale: DirectoryLocale) => string): string {
  const alternates: [string, string][] = DIRECTORY_LOCALES.map(({ code }) => [code, pathFor(code)]);
  alternates.push(["x-default", pathFor(DEFAULT_DIRECTORY_LOCALE)]);
  return alternates
    .map(([code, path]) => `<xhtml:link rel="alternate" hreflang="${code}" href="${STATIC_SEO_ORIGIN}${path}" />`)
    .join("");
}

// Partner-entered free text (a gallery photo's caption) landing in
// hand-built XML for the first time here — <loc> below is always a URL
// this module built itself from known-safe pieces (site origin, a known
// path shape, an id/slug), never free text, so nothing else in this file
// has needed escaping until now.
function escapeXml(text: string): string {
  return text.replace(/[&<>"']/g, (char) => {
    switch (char) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      default:
        return "&apos;";
    }
  });
}

function urlEntry(
  url: string,
  options: {
    alternates?: string;
    lastModified?: Date;
    changeFrequency: string;
    priority: number;
    images?: { url: string; caption?: string }[];
  },
): string {
  const parts = [`<loc>${url}</loc>`];
  if (options.alternates) parts.push(options.alternates);
  // The Google Images sitemap extension (see the xmlns:image declaration
  // below) — a listing's logo/gallery photos otherwise have no dedicated
  // discovery path into Google Images at all, only whatever a page crawl
  // happens to find. One <image:image> per photo — the extension allows
  // repeating it, unlike <image:loc> within one.
  for (const image of options.images ?? []) {
    const caption = image.caption ? `<image:caption>${escapeXml(image.caption)}</image:caption>` : "";
    parts.push(`<image:image><image:loc>${image.url}</image:loc>${caption}</image:image>`);
  }
  if (options.lastModified) parts.push(`<lastmod>${options.lastModified.toISOString()}</lastmod>`);
  parts.push(`<changefreq>${options.changeFrequency}</changefreq>`);
  parts.push(`<priority>${options.priority}</priority>`);
  return `<url>${parts.join("")}</url>`;
}

// Every language of every page is its own real, indexable URL (see
// directoryHomePath/directoryListingPath/categoryPath) — so each gets its
// own <url> entry, carrying hreflang alternates back to the other two
// (itself included, which is what a correct hreflang set requires) rather
// than one "canonical" URL with the others only referenced as alternates.
//
// Only the public directory is listed. The partner portal and the staff CRM
// both sit behind a login (and the portal declares itself noindex), so
// naming them here would only send crawlers to a sign-in form.
export async function buildSitemapXml(): Promise<string> {
  const [listings, categories] = await Promise.all([
    loadPublishedListings(),
    db.businessCategory.findMany({ orderBy: { name: "asc" }, select: { name: true } }),
  ]);
  const countByCategory = countListingsByCategory(listings);
  const countByIndustry = countListingsByIndustry(listings);
  // A category page's own content changes whenever any listing carrying it
  // is published or unpublished — the latest such date among its listings
  // is the honest lastmod for the category page itself, same reasoning as
  // a listing's own lastmod below.
  const latestPublishedByCategory = new Map<string, Date>();
  // Same idea, per city+state (or state-only) group, for the location pages
  // below — see findLocationBySlug/countListingsByCityState for why there's
  // no "empty location" case to skip the way the category loop below has
  // to. Keyed by the same combined label locationPath's own slug is built
  // from, so a listing with no city set still gets its own state-only key.
  const latestPublishedByLocation = new Map<string, Date>();
  // Same idea, per industry — like category, an industry can have zero
  // listings (see countListingsByIndustry), so the loop below skips those.
  const latestPublishedByIndustry = new Map<string, Date>();
  for (const { publishedAt, updatedAt, listing } of listings) {
    const date = publishedAt ?? updatedAt;
    for (const category of new Set(listing.categories)) {
      const latest = latestPublishedByCategory.get(category);
      if (!latest || date > latest) latestPublishedByCategory.set(category, date);
    }
    if (listing.state) {
      const label = locationLabel(listing.city, listing.state);
      const latest = latestPublishedByLocation.get(label);
      if (!latest || date > latest) latestPublishedByLocation.set(label, date);
    }
    if (listing.industry) {
      const latest = latestPublishedByIndustry.get(listing.industry);
      if (!latest || date > latest) latestPublishedByIndustry.set(listing.industry, date);
    }
  }

  const entries: string[] = [];

  for (const { code } of DIRECTORY_LOCALES) {
    entries.push(
      urlEntry(`${STATIC_SEO_ORIGIN}${directoryHomePath(code)}`, {
        alternates: languageAlternates(directoryHomePath),
        changeFrequency: "daily",
        priority: 0.8,
      }),
    );
  }

  // Shared lastmod for the four new aggregate pages below (categories/
  // locations index, products feed, news feed): each one's content is
  // derived from every published listing at once, so the most recent
  // publish/update across all of them is the honest lastmod for all four —
  // there's no single listing each page belongs to the way a category or
  // location page has one.
  let latestOverall: Date | undefined;
  for (const { publishedAt, updatedAt } of listings) {
    const date = publishedAt ?? updatedAt;
    if (!latestOverall || date > latestOverall) latestOverall = date;
  }

  for (const { code } of DIRECTORY_LOCALES) {
    entries.push(
      urlEntry(`${STATIC_SEO_ORIGIN}${directoryCategoriesIndexPath(code)}`, {
        alternates: languageAlternates(directoryCategoriesIndexPath),
        lastModified: latestOverall,
        changeFrequency: "daily",
        priority: 0.6,
      }),
    );
    entries.push(
      urlEntry(`${STATIC_SEO_ORIGIN}${directoryLocationsIndexPath(code)}`, {
        alternates: languageAlternates(directoryLocationsIndexPath),
        lastModified: latestOverall,
        changeFrequency: "daily",
        priority: 0.6,
      }),
    );
    entries.push(
      urlEntry(`${STATIC_SEO_ORIGIN}${directoryProductsPath(code)}`, {
        alternates: languageAlternates(directoryProductsPath),
        lastModified: latestOverall,
        changeFrequency: "daily",
        priority: 0.6,
      }),
    );
    entries.push(
      urlEntry(`${STATIC_SEO_ORIGIN}${directoryNewsPath(code)}`, {
        alternates: languageAlternates(directoryNewsPath),
        lastModified: latestOverall,
        changeFrequency: "daily",
        priority: 0.6,
      }),
    );
  }

  for (const { name } of categories) {
    // A category nobody has published into yet is noindex (see
    // buildCategoryMetadata) — listing it here would only send crawlers to
    // a page that then asks not to be indexed. It joins the moment a
    // published listing carries it, since every publish regenerates this.
    if (!(countByCategory.get(name) ?? 0)) continue;
    const categorySlug = slugify(name);
    for (const { code } of DIRECTORY_LOCALES) {
      entries.push(
        urlEntry(`${STATIC_SEO_ORIGIN}${categoryPath(categorySlug, code)}`, {
          alternates: languageAlternates((locale) => categoryPath(categorySlug, locale)),
          lastModified: latestPublishedByCategory.get(name),
          changeFrequency: "daily",
          priority: 0.7,
        }),
      );
    }
  }

  // Every city+state (or state-only) group at least one published listing
  // carries. Unlike categories, there's no separate admin-managed table to
  // iterate and no "nobody's published into it yet" case to skip (see
  // countListingsByCityState) — the set of groups below IS the count map's
  // own values.
  for (const { city, state } of countListingsByCityState(listings).values()) {
    const label = locationLabel(city, state);
    const locationSlug = slugify(label);
    for (const { code } of DIRECTORY_LOCALES) {
      entries.push(
        urlEntry(`${STATIC_SEO_ORIGIN}${locationPath(locationSlug, code)}`, {
          alternates: languageAlternates((locale) => locationPath(locationSlug, locale)),
          lastModified: latestPublishedByLocation.get(label),
          changeFrequency: "daily",
          priority: 0.7,
        }),
      );
    }
  }

  // Every industry at least one published listing carries. Like state
  // (and unlike category), countByIndustry only ever holds a key once some
  // listing actually carries it — nothing to skip here the way the empty-
  // category case above needs to.
  for (const industry of countByIndustry.keys()) {
    for (const { code } of DIRECTORY_LOCALES) {
      entries.push(
        urlEntry(`${STATIC_SEO_ORIGIN}${industryPath(industry, code)}`, {
          alternates: languageAlternates((locale) => industryPath(industry, locale)),
          lastModified: latestPublishedByIndustry.get(industry),
          changeFrequency: "daily",
          priority: 0.7,
        }),
      );
    }
  }

  // The public page only changes when a snapshot is approved, so the
  // publish time is the honest lastmod; updatedAt moves on every draft save
  // the public never sees, and a lastmod that lies gets ignored.
  for (const { slug, publishedAt, updatedAt, listing } of listings) {
    // Logo first (uncaptioned — it represents the business, not a specific
    // photo), then the gallery in its own display order, each with
    // whatever caption the partner gave it.
    const images: { url: string; caption?: string }[] = [
      ...(listing.logoUrl ? [{ url: `${STATIC_SEO_ORIGIN}${listingLogoPath(slug, publishedAt)}` }] : []),
      ...listing.photos.map((photo) => ({
        url: `${STATIC_SEO_ORIGIN}${directoryImagePath(photo.id)}`,
        caption: photo.caption || undefined,
      })),
    ];
    for (const { code } of DIRECTORY_LOCALES) {
      entries.push(
        urlEntry(`${STATIC_SEO_ORIGIN}${directoryListingPath(code, slug)}`, {
          alternates: languageAlternates((locale) => directoryListingPath(locale, slug)),
          lastModified: publishedAt ?? updatedAt,
          changeFrequency: "weekly",
          priority: 0.6,
          images,
        }),
      );
    }

    // Each of this listing's own sections is its own real page now (see
    // src/app/[locale]/[slug]/layout.tsx) — one entry per section per
    // locale, same as the listing's own About page above, just at a lower
    // priority (a sub-page of a listing, not the listing itself) and only
    // for a section this listing actually has something in (matching that
    // page's own notFound() guard — a sitemap entry for a page that 404s is
    // worse than no entry at all). News/Promotions presence ignores each
    // post's own current-vs-expired date (unlike the pages themselves,
    // which do filter by it): the sitemap only regenerates on
    // publish/unpublish, so it can't track an expiry date rolling over
    // between regenerations any more precisely than that.
    const hasNews = listing.updates.some((update) => update.kind === "NEWS");
    const hasPromotions = listing.updates.some((update) => update.kind === "PROMOTION");
    const sectionEntries: [boolean, (locale: DirectoryLocale) => string][] = [
      [listing.services.length > 0, (locale) => directoryListingServicesPath(locale, slug)],
      [listing.photos.length > 0, (locale) => directoryListingPhotosPath(locale, slug)],
      [listing.videos.length > 0, (locale) => directoryListingVideosPath(locale, slug)],
      [hasNews, (locale) => directoryListingNewsPath(locale, slug)],
      [hasPromotions, (locale) => directoryListingPromotionsPath(locale, slug)],
      [Boolean(listing.address || listing.operatingHours), (locale) => directoryListingVisitPath(locale, slug)],
      [listing.faqs.length > 0, (locale) => directoryListingFaqPath(locale, slug)],
    ];
    for (const [hasContent, pathFor] of sectionEntries) {
      if (!hasContent) continue;
      for (const { code } of DIRECTORY_LOCALES) {
        entries.push(
          urlEntry(`${STATIC_SEO_ORIGIN}${pathFor(code)}`, {
            alternates: languageAlternates(pathFor),
            lastModified: publishedAt ?? updatedAt,
            changeFrequency: "weekly",
            priority: 0.5,
          }),
        );
      }
    }
  }

  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n` +
    entries.join("\n") +
    `\n</urlset>\n`
  );
}

// Written to a temp file and renamed into place rather than written
// directly — rename is atomic on the same filesystem, so a request landing
// mid-regeneration always sees either the old complete file or the new
// complete one, never a half-written one (this file is served straight off
// disk by the web server, not proxied through anything that would buffer a
// partial read).
export async function regenerateSitemapFile(): Promise<void> {
  const xml = await buildSitemapXml();
  await mkdir(path.dirname(SITEMAP_PATH), { recursive: true });
  const tmpPath = `${SITEMAP_PATH}.tmp-${process.pid}`;
  await writeFile(tmpPath, xml, "utf8");
  await rename(tmpPath, SITEMAP_PATH);
}
